version: '3.7'
services:
  api:
    container_name: 'api'
    build: '.'
    ports:
      - '8080:8080'
    volumes:
      - './api:/go/src/app'
    depends_on:
      - 'mongo'
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    volumes:
      - ./data:/data
    ports:
      - '27100:27017'
  mongo_seed:
    image: 'mongo:latest'
    links:
      - mongo
    volumes:
      - ./data:/data
    command:
      mongoimport --host mongo --db dito --collection events --type json --file /data/event.json --jsonArray